name: main

on:
  push:
    branches: 
      - master
    schedule:
      - cron: '0 0 */7 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push (alpine)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/lyekumchew/snell-server:latest
            ghcr.io/lyekumchew/snell-server:alpine
      -
        name: Build and push (debian)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-debian
          platforms: linux/amd64
          push: true
          tags: ghcr.io/lyekumchew/snell-server:debian
